FROM registry.access.redhat.com/ubi8/ubi:latest
LABEL description="GOGS conteinerized binary working on ubi8"
MAINTAINER Dmitry Alekhin <dalekhin@redhat.com>
RUN mkdir /data
ADD https://dl.gogs.io/0.12.3/gogs_0.12.3_linux_amd64.tar.gz /tmp
RUN tar zxvf /tmp/gogs_0.12.3_linux_amd64.tar.gz -C /data
EXPOSE 3000
STOPSIGNAL SIGTERM
CMD ["/data/gogs/gogs", "web"]
